version: '2'
services:
  jhipsterrolesandauthorities-app:
    image: jhipsterrolesandauthorities
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://jhipsterrolesandauthorities-mysql:3306/jhipsterrolesandauthorities?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  jhipsterrolesandauthorities-mysql:
    extends:
      file: mysql.yml
      service: jhipsterrolesandauthorities-mysql
